name: 'playwright'
on:
  push:
    branches:
      - main
jobs:
  test-playwright:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run demo
        run: npm run playwright
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshot*.png
