on:
  push:
    branches:
      - main
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
      - run: npm install
      - name: Run demo
      - run: src/js/playwright/demo.js
      - name: Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: path/to/artifacts/screenshot*.png
